#!/usr/bin/env bash


file="$1"                       #ASCII text file generated by script AFM_gridData.py
pos="$2"                        # label of position in the ASCII table [pos]
data="$3"                       # column label of data [displacement]

vtk_rectilinearGrid -m point -p $pos ${file}

vtk_addRectilinearGridData -m point --vtk *_${pos}.vtr -v $data ${file}

